### ISSUE TITLE
[Bug]: Wasm target fails to compile with Kotlin 2.0 due to "IrTypeAliasSymbolImpl is already bound" for Instant

### ISSUE THREAD

**Issue by tomveich** [supabase-community/supabase-kt#1021]
### General Info

- [x] I checked for similar bug report
- [x] I am using the latest version
- [x] I checked the [troubleshooting](https://github.com/supabase-community/supabase-kt/blob/master/TROUBLESHOOTING.md) page for similar problems

### Version(s)

3.2.2, 3.2.1, 3.2.0

### Kotlin Target(s) and their respective versions

Wasm

### What happened? (include your code)

Environment:

    Kotlin Version: 2.2.0

    Supabase-kt Version: 3.2.2

    Compose Multiplatform Version: 1.8.2

    Target: Wasm (wasmJs)

Bug Description:

After migrating a Kotlin Multiplatform project from Kotlin 1.9.x to 2.0.0, the build fails specifically for the wasmJs target. The project compiles and runs correctly on the Android/JVM target.

The migration involved updating code to use the new kotlin.time.Instant in place of the now-deprecated kotlinx.datetime.Instant. The compilation error suggests that there is a dependency conflict where two different libraries are attempting to define a typealias for the old kotlinx.datetime.Instant, causing the Wasm compiler to fail.

This points to a potential transitive dependency within supabase-kt that has not been fully updated to align with the new Kotlin 2.0 library ecosystem, causing a conflict that is only surfaced by the stricter Wasm linker.

Steps to Reproduce:

    Create a Kotlin Multiplatform project targeting Android and Wasm (wasmJs).

    Set the project's Kotlin version to 2.2.0.

    Add the latest supabase-kt dependencies (version 3.2.2).

    In commonMain, add a simple piece of code that references kotlin.time.Clock.System.now().

    Attempt to compile the Wasm target by running the Gradle task: ./gradlew :composeApp:compileDevelopmentExecutableKotlinWasmJs

Expected Behavior:

The project should compile successfully for the wasmJs target, just as it does for the Android target.

Actual Behavior:

The Wasm compilation task fails with the following error:

e: java.lang.IllegalStateException: IrTypeAliasSymbolImpl is already bound. Signature: kotlinx.datetime/Instant|null[0]. Owner: TYPEALIAS name:Instant visibility:public expandedType:kotlin.time.Instant
    at org.jetbrains.kotlin.ir.symbols.impl.IrSymbolBase.bind(IrSymbolImpl.kt:68)
    at org.jetbrains.kotlin.ir.declarations.impl.IrTypeAliasImpl.<init>(IrTypeAliasImpl.kt:48)
    at org.jetbrains.kotlin.ir.declarations.IrFactory.createTypeAlias(IrFactory.kt:346)
    ...

Additional Context:

    The official release notes for supabase-kt version 3.2.0 mention: "Note: KotlinX Datetime Version 0.7.0 is not compatible for now! An update to KotlinX Serialization is required." This seems highly related to the issue.

    Attempts to work around this by forcing dependency versions (resolutionStrategy) or excluding the transitive kotlinx-datetime dependency have not been successful so far.

    The issue appears to be specific to the Wasm toolchain's dependency resolution and linking process.

I wasn't able to resolve this bug in my KMP project, and I'm not sure what to do right now. Do you suggest to migrate the entire project to the old pre-kotlin-2.0 kotlinx.datetime system or wait for supabase-kt to adopt the current kotlin.time classes? 
Thank you for your work on this great library!

**Comment by tomveich** [comment]
Hello,
Thank you for the prompt response. Upon further investigation, I found out what was the problem, and it wasn't `supabase-kt`.

My project has been using `kotlinx.datetime.Clock` and `kotlinx.datetime.Instant`. Then, after updating Kotlin to the latest version, these became deprecated and Android Studio became suggesting to change the imports to `kotlin.time.Clock` and `kotlin.time.Instant`. I quickly found out that the new `kotlin.time` system wasn't compatible with the older `kotlinx.datetime` system supabase-kt is using (because of errors regarding `Instant`) and therefore I migrated the Instant back to `kotlinx.datetime`. However, I didn't realize I kept using `Clock` from the newer `kotlin.time` system, which is likely internally bringing up the new `kotlin.time.Instant` which supabase-kt is incompatible with. Downgrading my entire project to kotlinx.datetime fixed this strange issue. 

Sorry for opening the ticket, and thank you again for your fantastic work on the library :)
